In [48]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

In [4]:
df_all = pd.read_csv('df_all.csv')
df_all.head()

name_dept  code_dept name_municip  code_municip  year_cohort  \
0  Antioquia          5     Medellin          5001         2011   
1  Antioquia          5     Medellin          5001         2012   
2  Antioquia          5     Medellin          5001         2013   
3  Antioquia          5     Medellin          5001         2014   
4  Antioquia          5     Medellin          5001         2015   

   desertion_perc  desertion_no  latitude  longitude  region  ...  \
0            3.69  15505.545380  6.291389 -75.536111  Andina  ...   
1            3.37  13949.572740  6.291389 -75.536111  Andina  ...   
2            3.39  13691.623970  6.291389 -75.536111  Andina  ...   
3            1.80   7139.044301  6.291389 -75.536111  Andina  ...   
4            3.58  14014.374610  6.291389 -75.536111  Andina  ...   

   dane_doc_21  dane_doc_22  dane_doc_23  dane_doc_24  dane_doc_25  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   dane_doc_26  dane_doc_27  pobr_ipm  pobr_imp_cabecera  pobr_ipm_cen_pobl  
0          NaN          NaN       NaN                NaN                NaN  
1          NaN          NaN       NaN                NaN                NaN  
2          NaN          NaN       NaN                NaN                NaN  
3          NaN          NaN       NaN                NaN                NaN  
4          NaN          NaN       NaN                NaN                NaN  

[5 rows x 176 columns]

In [5]:
df_all.columns[0:100]

Index(['name_dept', 'code_dept', 'name_municip', 'code_municip', 'year_cohort',
       'desertion_perc', 'desertion_no', 'latitude', 'longitude', 'region',
       'icbf_cobert_inmu_dtp_hep_1', 'icbf_cobert_inmu_tv_1',
       'icbf_cobert_vacu_bcg_nac_v', 'icbf_cobert_vacu_fib_ama_1',
       'icbf_cobert_vacu_haem_b_1', 'icbf_cobert_vacu_neumco_1',
       'icbf_cobert_vacu_polio_1', 'icbf_cobert_vacu_rotav_1',
       'icbf_num_afi_reg_contr_18', 'icbf_num_afi_reg_subs_18',
       'icbf_num_nin_adol_desvinc', 'icbf_raz_mort_mater_x100m_nac_viv',
       'icbf_tasa_fecun_nin_10_14', 'icbf_tasa_fecun_nin_15_19',
       'icbf_tasa_mort_1_1000_nac_v', 'icbf_tasa_mort_fetal',
       'icbf_tasa_mort_desnut_5', 'icbf_tasa_mort_eda_5',
       'icbf_tasa_mort_era_5', 'cr_amenaza', 'cr_delito_sexual',
       'cr_homicidio', 'cr_hurto_comercio', 'cr_hurto_persona',
       'cr_hurto_residencia', 'cr_lesiones_personales', 'cr_terrorismo',
       'cr_violencia_intrafamiliar', 'cr_total_crimes', 'sa_pun

In [32]:
df_all['code_municip'].unique()

array([ 5001,  5002,  5004, ..., 99524, 99624, 99773], dtype=int64)

In [33]:
in_mun_code = 99524
var = 'desertion_perc'
df_filtered = df_all[df_all['code_municip'] == in_mun_code]
print(df_filtered.shape)
df_filtered.head()


(9, 176)


name_dept  code_dept  name_municip  code_municip  year_cohort  \
7833   Vichada         99  La Primavera         99524         2011   
7834   Vichada         99  La Primavera         99524         2012   
7835   Vichada         99  La Primavera         99524         2013   
7836   Vichada         99  La Primavera         99524         2014   
7837   Vichada         99  La Primavera         99524         2015   

      desertion_perc  desertion_no  latitude  longitude     region  ...  \
7833            4.78    111.033932  5.490556 -70.409167  Orinoquia  ...   
7834            3.88     86.022103  5.490556 -70.409167  Orinoquia  ...   
7835            7.41    176.362372  5.490556 -70.409167  Orinoquia  ...   
7836            5.97    142.393574  5.490556 -70.409167  Orinoquia  ...   
7837            6.94    175.788361  5.490556 -70.409167  Orinoquia  ...   

      dane_doc_21  dane_doc_22  dane_doc_23  dane_doc_24  dane_doc_25  \
7833          NaN          NaN          NaN          NaN          NaN   
7834          NaN          NaN          NaN          NaN          NaN   
7835          NaN          NaN          NaN          NaN          NaN   
7836          NaN          NaN          NaN          NaN          NaN   
7837          NaN          NaN          NaN          NaN          NaN   

      dane_doc_26  dane_doc_27  pobr_ipm  pobr_imp_cabecera  pobr_ipm_cen_pobl  
7833          NaN          NaN       NaN                NaN                NaN  
7834          NaN          NaN       NaN                NaN                NaN  
7835          NaN          NaN       NaN                NaN                NaN  
7836          NaN          NaN       NaN                NaN                NaN  
7837          NaN          NaN       NaN                NaN                NaN  

[5 rows x 176 columns]

In [148]:
types=['Transición', 'Primaria', 'Media', 'Secundaria']
year = 2019
df_types = df_filtered[df_filtered['year_cohort']==year]

label_desercion = str(np.round(df_types['desertion_perc'].to_numpy()[0],2))+' %'
y_plot = df_types[[
    
              'me_desercion_transicion'          , 
              'me_desercion_primaria', 
              'me_desercion_media',
              'me_desercion_secundaria',
             ]].to_numpy()

derc_perc = [x/sum(y_plot) for x in y_plot]

# cobertura
tempval = df_types['me_cobertura_neta'].to_numpy()[0]
label_cobertura = str(np.round(tempval,2))+' %'
y_plot_2 = df_types[[
              'me_cobertura_neta_transicion'          , 
              'me_cobertura_neta_primaria', 
              'me_cobertura_neta_media',
              'me_cobertura_neta_secundaria',
             ]].to_numpy()

cob_perc = [x*tempval/sum(y_plot_2) for x in y_plot_2]
print(y_plot_2)
print(cob_perc)
# aprobación


label_aprob = str(np.round(df_types['me_aprobacion'].to_numpy()[0],2))+' %'
y_plot_3 = df_types[[
              'me_aprobacion_transicion'          , 
              'me_aprobacion_primaria', 
              'me_aprobacion_media',
              'me_aprobacion_secundaria',
             ]].to_numpy()

aprob_perc = [x/sum(y_plot_3) for x in y_plot_3]

print(y_plot_3)
print(aprob_perc)

[[48.2412 94.0959 29.5612 56.6921]]
[array([91.1195, 91.1195, 91.1195, 91.1195])]
[[94.375  81.2147 93.3054 91.3151]]
[array([1., 1., 1., 1.])]


In [145]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

labels = types

# Create subplots: use 'domain' type for Pie subplot
fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]])
fig.add_trace(go.Pie(labels=labels, values=derc_perc, name="Desercion"),
              1, 1)
fig.add_trace(go.Pie(labels=labels, values=aprob_perc, name="Aprobacion"),
              1, 2)

# Use `hole` to create a donut-like pie chart
fig.update_traces(hole=.4, hoverinfo="label+percent+name")

fig.update_layout(
    title_text="Deserción y Cobertura Escolar 2019",
    # Add annotations in the center of the donut pies.
    annotations=[dict(text='Deserción:', x=0.15, y=0.55, font_size=20, showarrow=False),
                 dict(text=label_desercion, x=0.17, y=0.48, font_size=20, showarrow=False),
                 dict(text='Cobertura:', x=0.85, y=0.55, font_size=20, showarrow=False),
                 dict(text=cob_perc, x=0.84, y=0.48, font_size=20, showarrow=False),
                ])
fig.show()

ValueError: 
    Invalid value of type 'builtins.list' received for the 'text' property of layout.annotation
        Received value: [array([1., 1., 1., 1.])]

    The 'text' property is a string and must be specified as:
      - A string
      - A number that will be converted to a string

In [31]:
fig = go.Figure(data=go.Scatter(x=df_filtered['year_cohort'],
                                y=df_filtered['desertion_perc'] ))
fig.show()

Useful later

In [59]:
fig = go.Figure([go.Bar(x=types, y=new_perc)])
fig.update_layout(barmode='stack')
fig.show()

In [73]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Bar(
    x=[new_perc[0]],
    y=[1],
    name=types[0],
    orientation='h',
))

fig.add_trace(go.Bar(
    x=[new_perc[1]],
    y=[1],
    name=types[1],
    orientation='h',
))

fig.add_trace(go.Bar(
    x=[new_perc[2]],
    y=[1],
    name=types[2],
    orientation='h',
))

fig.add_trace(go.Bar(
    x=[new_perc[3]],
    y=[1],
    name=types[3],
    orientation='h',
))

fig.update_layout(barmode='stack')
fig.show()